### ISSUE TITLE
Missing libgcc_s_seh-1.dll

### ISSUE THREAD

**Issue by eeyrw** [lilipads/gradient_descent_viz#1]
Fail to run windows version app with error:
![image](https://user-images.githubusercontent.com/2088817/84584335-a4d2ce80-ae35-11ea-98e2-a2885b898254.png)
"Can not find libgcc_s_seh-1.dll"

**Comment by huaji0353** [comment]
open anconda cmd
cd {dir}
gradient_descent_visualization.exe

solved

**Comment by eeyrw** [comment]
I am not a fan of anaconda.

**Comment by libichong** [comment]
[dlls.zip](https://github.com/lilipads/gradient_descent_viz/files/5388472/dlls.zip)
 To solve the issue, you need to copy the attached files to the running folder. The dlls were copied from mingw64.

**Comment by skyemoor** [comment]
> 
> 
> open anaconda cmd
> cd {dir}
> gradient_descent_visualization.exe
> 
> solved

For those who are a little puzzled;
1. Open the Anaconda Powershell
2. cd to the directory you extracted this to
3. .\gradient_descent_visualization.exe
