### ISSUE TITLE
more optimize method and pyqtgraph implemention

### ISSUE THREAD

**Issue by huaji0353** [lilipads/gradient_descent_viz#2]
good works !

some enhance you can reference:
surface visualization like https://github.com/tomgoldstein/loss-landscape

training loss animation visualization
https://github.com/joshuagruenstein/atlas
https://github.com/spencer-hann/Loss_Surface_Visualizer
https://www.deeplearning.ai/ai-notes/optimization

**Comment by lilipads** [comment]
thank you for sharing!
