### ISSUE TITLE
Use of this tool to illustrate during a presentation

### ISSUE THREAD

**Issue by Guibeau** [lilipads/gradient_descent_viz#7]
Hi,
Sry I'm new to this website and i don't know if that's the right section to post in for this, but i have a presentation for my first year in master of mathematics, and i wanted to ask for permission to show images/videos of this tool during a presentation on gradient descent methods.
Thank you for helping me understand these better anyway,
Cordially,
Guillaume Bauman.

**Comment by lilipads** [comment]
sure, as long as you cite the source, go ahead and use it!
